"""Policy regressions use temporary Git repositories and generated bytes only."""

import contextlib
import io
import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from scripts.ci import repository_guard as guard


class RepositoryGuardTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.git("init", "--quiet")

    def git(self, *args):
        return subprocess.run(
            ["git", "-C", str(self.root), *args], check=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )

    def write(self, path, content, tracked=True):
        target = self.root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content.encode() if isinstance(content, str) else content)
        if tracked:
            self.git("add", "--force", "--", path)
        return target

    def categories(self):
        return {finding.category for finding in guard.audit(self.root)}

    def fixture(self, content=None, recipe="checkerboard-8x8-v1"):
        path = "tests/fixtures/synthetic/checkerboard.ppm"
        self.write(path, guard.generated_fixture(recipe) if content is None else content)
        self.write(guard.MANIFEST, json.dumps({
            "schema": 1, "fixtures": [{"path": path, "recipe": recipe}],
        }))
        return path

    def test_clean_source_and_documentation_pass(self):
        self.write("server/app/media/health.py", "def healthy():\n    return True\n")
        self.write("web/src/recordings/view.ts", "export const playback = true;\n")
        self.write("server/README.md", "Sentry and telemetry_enabled settings are prohibited.\n")
        self.write("docs/policy.md", "Do not depend on @sentry/browser or mixpanel.\n")
        self.write(".env.example", "SLACK_WEBHOOK_URL=\n")
        self.assertEqual(self.categories(), set())

    def test_deterministic_synthetic_fixture_passes(self):
        self.fixture()
        self.assertEqual(self.categories(), set())
        self.assertEqual(guard.generated_fixture("checkerboard-8x8-v1").count(b"\n"), 67)

    def test_fixture_without_manifest_fails(self):
        self.write("tests/fixtures/synthetic/image.ppm", guard.generated_fixture("checkerboard-8x8-v1"))
        self.assertIn("unproven-media", self.categories())

    def test_fixture_modification_fails_even_with_declared_recipe(self):
        self.fixture(b"P3\n1 1\n255\n0 0 0\n")
        self.assertIn("fixture-content-mismatch", self.categories())

    def test_self_declared_hash_or_generator_cannot_establish_provenance(self):
        path = self.fixture()
        for metadata in ({"sha256": "0" * 64}, {"generator": "python evil.py"}):
            with self.subTest(metadata=metadata):
                self.write(guard.MANIFEST, json.dumps({
                    "schema": 1, "fixtures": [{"path": path, **metadata}],
                }))
                self.assertIn("invalid-fixture-manifest", self.categories())
                self.assertIn("unproven-media", self.categories())

    def test_manifest_schema_paths_duplicates_and_recipes_are_constrained(self):
        path = self.fixture()
        bad_entries = [
            [{"path": path, "recipe": "unreviewed"}],
            [{"path": "tests/fixtures/synthetic/../outside.ppm", "recipe": "checkerboard-8x8-v1"}],
            [{"path": path, "recipe": "checkerboard-8x8-v1", "pixels": [1, 2, 3]}],
            [{"path": path, "recipe": "checkerboard-8x8-v1"}] * 2,
            [{"path": "tests/fixtures/synthetic/missing.ppm", "recipe": "checkerboard-8x8-v1"}],
        ]
        for entries in bad_entries:
            with self.subTest(entries=entries):
                self.write(guard.MANIFEST, json.dumps({"schema": 1, "fixtures": entries}))
                self.assertIn("invalid-fixture-manifest", self.categories())
        self.write(guard.MANIFEST, '{"schema":1,"schema":1,"fixtures":[]}')
        self.assertIn("invalid-fixture-manifest", self.categories())

    def test_generated_image_outside_synthetic_fixture_tree_fails(self):
        self.write("tests/fixtures/image.ppm", guard.generated_fixture("checkerboard-8x8-v1"))
        self.assertIn("unproven-media", self.categories())

    def test_ui_image_outside_fixture_tree_remains_allowed(self):
        self.write("web/public/icon.png", b"\x89PNG\r\n\x1a\n" + bytes(20))
        self.assertEqual(self.categories(), set())

    def test_misnamed_image_and_capture_magic_fail(self):
        for path, data, category in [
            ("server/assets/payload.dat", b"\x89PNG\r\n\x1a\n", "misnamed-media"),
            ("tests/fixtures/synthetic/payload.bin", b"GIF89a", "unproven-media"),
            ("web/public/payload.bin", b"\x00\x00\x00\x18ftypisomxxxx", "unproven-media"),
        ]:
            with self.subTest(path=path):
                self.write(path, data)
                self.assertIn(category, self.categories())

    def test_known_secret_formats_fail_in_any_file(self):
        # Split prefixes and construct tokens only in temporary repositories.
        values = [
            "-----" + "BEGIN PRIVATE KEY" + "-----",
            "https://hooks." + "slack.com/services/" + "T" * 9 + "/" + "B" * 9 + "/" + "c" * 24,
            "xox" + "b-" + "a" * 24,
            "tskey-" + "auth-" + "a" * 24,
            "gh" + "p_" + "a" * 36,
            "github_" + "pat_" + "a" * 60,
            "AK" + "IA" + "A" * 16,
            "AI" + "za" + "a" * 35,
        ]
        for value in values:
            with self.subTest(prefix=value[:3]):
                self.write("docs/example.md", "Example\n" + value + "\n")
                findings = guard.audit(self.root)
                self.assertTrue(any(item.category == "secret-format" and item.line == 2 for item in findings))

    def test_secret_path_rules_override_force_add_and_fixture_allowance(self):
        self.write(".gitignore", ".env*\n*.pem\nsecrets/\n")
        for path in [
            ".env", ".ENV.EXAMPLE", "web/.env.local", "tests/fixtures/synthetic/server.pem",
            "tests/fixtures/synthetic/Secrets/image.png", "agent/.netrc",
            "agent/credentials.json", "agent/id_ed25519.pub", "agent/CERTS/anything",
            "infra/.env.production/config.json",
        ]:
            with self.subTest(path=path):
                self.write(path, "redacted")
                matching = [finding for finding in guard.audit(self.root) if finding.category == "sensitive-path"]
                self.assertEqual(len(matching), len([p for p in guard.tracked_files(self.root) if p != ".gitignore"]))

    def test_example_config_and_fixture_media_do_not_bypass_secret_scan(self):
        secret = "gh" + "p_" + "a" * 36
        self.write(".env.example", "TOKEN=" + secret)
        self.fixture(guard.generated_fixture("checkerboard-8x8-v1") + secret.encode())
        categories = self.categories()
        self.assertIn("secret-format", categories)
        self.assertIn("fixture-content-mismatch", categories)

    def test_runtime_files_and_inventory_are_rejected(self):
        paths = [
            "recordings/readme.json", "agent/runtime/state.json", "agent/state.db-wal",
            "tests/fixtures/synthetic/hardware-inventory.json", "owner-face-embedding.npy",
        ]
        for path in paths:
            self.write(path, "{}")
        self.assertEqual(sum(f.category == "runtime-data-path" for f in guard.audit(self.root)), len(paths))
        self.write("server/state.bin", b"SQLite format 3\0")
        self.assertIn("runtime-data-content", self.categories())

    def test_symlink_and_symlink_parent_are_not_followed(self):
        target = self.root / "private-target"
        target.write_text("private content")
        (self.root / "link").symlink_to(target)
        self.git("add", "link")
        self.assertIn("unsafe-file-type", self.categories())
        self.write("server/app.py", "pass\n")
        (self.root / "server/app.py").unlink()
        (self.root / "server").rmdir()
        (self.root / "server").symlink_to(self.root, target_is_directory=True)
        self.assertIn("unreadable-or-unsafe-file", self.categories())

    def test_submodule_is_rejected(self):
        self.git("update-index", "--add", "--cacheinfo", "160000," + "1" * 40 + ",vendor")
        self.assertIn("unsafe-file-type", self.categories())

    def test_dependency_and_transitive_lock_signatures_fail(self):
        cases = [
            ("web/package.json", '{"dependencies":{"@sentry/browser":"1.0"}}'),
            ("agent/uv.lock", '[[package]]\nname = "sentry-sdk"\nversion = "1.0"'),
            ("server/requirements.txt", "posthog==1.0\n"),
            ("package-lock.json", '{"node_modules/mixpanel":{"version":"1.0"}}'),
            ("web/pnpm-lock.yaml", "packages:\n  '@firebase/analytics@1.0': {}\n"),
        ]
        for path, content in cases:
            with self.subTest(path=path):
                self.write(path, content)
        self.assertEqual(sum(f.category == "prohibited-reporting" for f in guard.audit(self.root)), len(cases))

    def test_sources_and_disabled_opt_in_reporting_configs_fail(self):
        cases = [
            ("server/app.py", "import sentry_sdk\n"),
            ("web/src/README.ts", 'import x from "@segment/analytics-next";'),
            ("infra/service.env", "TELEMETRY_ENABLED=false\n"),
            ("agent/settings.toml", "crash_report_url = ''\n"),
            ("web/settings.json", '{"analytics": {"enabled": false}}'),
            ("infra/compose.yaml", "environment:\n  TRACKING_OPT_IN: false\n"),
        ]
        for path, content in cases:
            self.write(path, content)
        self.assertEqual(sum(f.category == "prohibited-reporting" for f in guard.audit(self.root)), len(cases))

    def test_local_object_tracking_settings_are_allowed(self):
        self.write("server/settings.toml", "tracking = true\ntracking_enabled = true\nenable_tracking = true\n")
        self.write("agent/settings.json", '{"tracking": {"enabled": true}}')
        self.assertEqual(self.categories(), set())

    def test_root_example_config_cannot_enable_reporting(self):
        self.write(".env.example", "TELEMETRY_ENABLED=false\nANALYTICS_OPT_IN=false\n")
        self.assertEqual(sum(f.category == "prohibited-reporting" for f in guard.audit(self.root)), 2)

    def test_generated_ignored_bundle_is_inspected(self):
        self.write(".gitignore", "dist/\nbuild/\n")
        self.write("web/dist/assets/app.js", 'window["posthog"].capture("event");', tracked=False)
        self.write("agent/build/package.gz", b"\x1f\x8b" + bytes(10), tracked=False)
        self.assertIn("prohibited-reporting", self.categories())
        self.assertIn("opaque-runtime-package", self.categories())

    def test_bundle_symlink_is_not_followed(self):
        (self.root / "web").mkdir()
        (self.root / "web/dist").symlink_to("/tmp", target_is_directory=True)
        self.assertIn("unreadable-or-unsafe-file", self.categories())

    def test_unreadable_and_oversized_files_fail_closed(self):
        path = self.write("server/app.py", "pass\n")
        with mock.patch.object(guard, "MAX_BYTES", 1):
            self.assertIn("unreadable-or-unsafe-file", self.categories())
        path.unlink()
        self.assertIn("unreadable-or-unsafe-file", self.categories())

    def test_total_size_and_file_count_limits_fail_closed(self):
        self.write("server/app.py", "pass\n")
        self.write("server/other.py", "pass\n")
        with mock.patch.object(guard, "MAX_TOTAL_BYTES", 8):
            self.assertEqual(self.categories(), {"scan-limit"})
        with mock.patch.object(guard, "MAX_FILES", 1):
            self.assertEqual(self.categories(), {"scan-limit"})

    def test_cli_diagnostics_never_disclose_path_or_values(self):
        secret = "tskey-" + "auth-" + "a" * 24
        self.write("docs/private-deployment-name.md", secret)
        output = io.StringIO()
        with mock.patch("sys.argv", ["repository_guard.py", "--root", str(self.root)]):
            with contextlib.redirect_stdout(output):
                self.assertEqual(guard.main(), 1)
        self.assertRegex(output.getvalue(), r"^secret-format file=\d+ line=1\n$")
        self.assertNotIn(secret, output.getvalue())
        self.assertNotIn("private-deployment", output.getvalue())

    def test_cli_scan_failures_are_fixed_diagnostics(self):
        output = io.StringIO()
        with mock.patch("sys.argv", ["repository_guard.py", "--root", str(self.root / "missing")]):
            with contextlib.redirect_stdout(output):
                self.assertEqual(guard.main(), 1)
        self.assertEqual(output.getvalue(), "repository-scan-failed file=0 line=0\n")


if __name__ == "__main__":
    unittest.main()
