"""Owner singleton/quality/privacy tests use generated bytes, never real faces."""

from contextlib import contextmanager
from dataclasses import replace
from datetime import datetime, timedelta, timezone
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import TestCase
from unittest.mock import patch
from uuid import UUID, uuid4
import asyncio
import json
import os
import socket
import sqlite3
import stat
import threading

from app.detection.owner.contracts import (Comparison, DenyOwner, FaceCandidate, ModelProvenance,
                                           Operation, OwnerError, Verdict, VerificationReason)
from app.detection.owner.service import OwnerVerificationService
from app.detection.owner.store import _MIGRATIONS, EnrollmentStatus, OwnerTemplateStore
from app.audit.runtime import AuditRetentionRuntime
from app.detection.quality import Execution, QualityGate
from tests.test_detector_quality import SOURCE, assess, calibrated_policy, context, synthetic_person


NOW = datetime(2026, 1, 1, tzinfo=timezone.utc)
MIGRATION = _MIGRATIONS[0]
PROVENANCE = ModelProvenance("generated-test-adapter", "fixture-1", "Apache-2.0", "Apache-2.0",
                             "https://example.invalid/generated-fixture", "a" * 64, "b" * 64, UUID(int=99))


class SyntheticAuthorizer:
    allowed = True
    def require_owner(self, operation):
        if not self.allowed:
            raise OwnerError("OWNER_AUTHORIZATION_REQUIRED")
        return UUID(int=123)


class SyntheticVerifier:
    provenance = PROVENANCE
    def __init__(self):
        self.template = b"synthetic-owner-template-v1"
        self.outcome = Comparison(Verdict.MATCH, .99)
        self.seen_templates = []
        self.candidates = []
        self.callback = None

    def enroll(self, crop):
        self.candidates.append(crop.pixels)
        return self.template

    def compare(self, crop, template):
        self.candidates.append(crop.pixels)
        self.seen_templates.append(template)
        if self.callback:
            self.callback()
        return self.outcome

    def forget_candidate(self):
        self.candidates.clear()


class OwnerTests(TestCase):
    def setUp(self):
        self.temp = TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name) / "private"
        self.root.mkdir(mode=0o700)
        self.authorizer = SyntheticAuthorizer()
        self.reserved = False
        self.denied = False
        self.store = self.open_store()
        self.addCleanup(lambda: self.store.close())
        self.verifier = SyntheticVerifier()
        self.service = OwnerVerificationService(self.store, self.verifier)
        self.gate = QualityGate(SOURCE, calibrated_policy("owner_verification"))
        assess(self.gate, synthetic_person(0))
        self.candidate = FaceCandidate(uuid4(), synthetic_person(1))
        self.decision = self.service.assess(self.candidate, self.gate, context=context(self.candidate.crop))

    @contextmanager
    def reservation(self):
        if self.denied:
            raise OwnerError("STORAGE_HARD_STOP")
        if self.reserved:
            raise AssertionError("nested reservation")
        self.reserved = True
        try:
            yield
        finally:
            self.reserved = False

    def open_store(self, **kwargs):
        return OwnerTemplateStore(kwargs.get("root", self.root), max_template_bytes=1024,
                                  reservation=self.reservation, authorizer=kwargs.get("authorizer", self.authorizer))

    def enroll(self):
        return self.service.enroll(self.candidate, self.gate, self.decision,
                                   expected_generation=self.store.status().generation, at=NOW)

    def test_default_owner_boundary_denies_enrollment_and_delete(self):
        self.store._authorizer = DenyOwner()
        with self.assertRaises(OwnerError):
            self.enroll()
        with self.assertRaises(OwnerError):
            self.store.delete(expected_generation=0, at=NOW)
        self.assertFalse(self.store.status().enrolled)

    def test_unauthorized_enrollment_never_reads_private_state(self):
        self.store._authorizer = DenyOwner()
        reads = []
        status = OwnerTemplateStore.status

        def recording(store):
            reads.append(True)
            return status(store)

        with patch.object(OwnerTemplateStore, "status", recording):
            with self.assertRaisesRegex(OwnerError, "OWNER_AUTHORIZATION_REQUIRED"):
                self.service.enroll(self.candidate, self.gate, self.decision,
                                    expected_generation=0, at=NOW)
        self.assertEqual(reads, [])

    def test_replacement_requires_the_replace_right_from_the_same_owner(self):
        self.enroll()
        granted = []

        class SingleRight:
            def require_owner(inner, operation):
                granted.append(operation)
                if operation is Operation.REPLACE:
                    raise OwnerError("OWNER_AUTHORIZATION_REQUIRED")
                return UUID(int=123)

        self.store._authorizer = SingleRight()
        with self.assertRaisesRegex(OwnerError, "OWNER_AUTHORIZATION_REQUIRED"):
            self.enroll()
        self.assertEqual(granted, [Operation.ENROLL, Operation.REPLACE])
        self.assertEqual(self.store.status(), EnrollmentStatus(True, 1))

    def test_private_persistence_and_audited_lifecycle(self):
        self.assertEqual(self.enroll().generation, 1)
        self.verifier.template = b"synthetic-owner-template-v2"
        self.assertEqual(self.enroll().generation, 2)
        self.assertEqual(self.store.delete(expected_generation=2, at=NOW).generation, 3)
        rows = self.store._db.execute("SELECT operation,generation FROM owner_template_audit ORDER BY id").fetchall()
        self.assertEqual([tuple(row) for row in rows], [(Operation.ENROLL, 1), (Operation.REPLACE, 2), (Operation.DELETE, 3)])
        self.assertIsNone(self.store._load_for_verification())
        self.assertEqual(stat.S_IMODE((self.root / "owner-template.sqlite3").stat().st_mode), 0o600)
        self.store.close()
        self.store = self.open_store()
        self.assertFalse(self.store.status().enrolled)
        self.assertEqual(self.store.status().generation, 3)

    def test_private_audit_retention_is_bounded_and_preserves_template(self):
        retention_now = datetime.now(timezone.utc)
        self.assertEqual(self.service.enroll(
            self.candidate, self.gate, self.decision,
            expected_generation=0, at=retention_now,
        ).generation, 1)
        old = (retention_now - timedelta(days=91)).isoformat()
        boundary = (retention_now - timedelta(days=89)).isoformat()
        actor = str(UUID(int=123))
        self.store._db.execute(
            "INSERT INTO owner_template_audit(at,actor,operation,generation) VALUES(?,?,?,?)",
            (old, actor, Operation.REPLACE, 2),
        )
        self.store._db.execute(
            "INSERT INTO owner_template_audit(at,actor,operation,generation) VALUES(?,?,?,?)",
            (boundary, actor, Operation.REPLACE, 3),
        )

        # The production scheduler invokes the private store on its bounded
        # worker; use that same cross-thread maintenance path here.
        self.assertEqual(1, asyncio.run(
            AuditRetentionRuntime(self.store).startup_cleanup()
        ))
        rows = self.store._db.execute(
            "SELECT at FROM owner_template_audit ORDER BY at"
        ).fetchall()
        self.assertEqual([boundary, retention_now.isoformat()],
                         [row["at"] for row in rows])
        self.assertEqual(EnrollmentStatus(True, 1), self.store.status())

    def test_replacement_never_uses_old_template(self):
        self.enroll()
        old = self.service.verify(self.candidate, self.gate, self.decision)
        self.assertTrue(self.service.is_current(old))
        self.verifier.template = b"synthetic-owner-template-v2"
        self.enroll()
        self.assertFalse(self.service.is_current(old))
        self.service.verify(self.candidate, self.gate, self.decision)
        self.assertEqual(self.verifier.seen_templates, [b"synthetic-owner-template-v1", b"synthetic-owner-template-v2"])

    def test_deleted_template_invalidates_inflight_result(self):
        self.enroll()
        self.verifier.callback = lambda: self.store.delete(expected_generation=1, at=NOW)
        result = self.service.verify(self.candidate, self.gate, self.decision)
        self.assertEqual(result.verdict, Verdict.UNKNOWN)
        self.assertEqual(result.reason, VerificationReason.TEMPLATE_CHANGED)
        self.assertFalse(self.service.is_current(result))
        self.assertEqual(self.verifier.candidates, [])

    def test_low_quality_skips_both_positive_and_negative_comparisons(self):
        self.enroll()
        dark = FaceCandidate(uuid4(), synthetic_person(2, condition="dark"))
        decision = self.service.assess(dark, self.gate, context=context(dark.crop))
        for verdict in (Verdict.MATCH, Verdict.NO_MATCH):
            self.verifier.outcome = Comparison(verdict, .99)
            result = self.service.verify(dark, self.gate, decision)
            self.assertEqual(result.verdict, Verdict.UNKNOWN)
        self.assertEqual(self.verifier.seen_templates, [])

    def test_same_frame_different_crop_cannot_reuse_quality_ticket(self):
        self.enroll()
        dark = FaceCandidate(uuid4(), synthetic_person(1, condition="dark"))
        result = self.service.verify(dark, self.gate, self.decision)
        self.assertEqual(result.verdict, Verdict.UNKNOWN)
        self.assertEqual(self.verifier.seen_templates, [])
        with self.assertRaisesRegex(OwnerError, "QUALITY_UNAVAILABLE"):
            self.service.enroll(dark, self.gate, self.decision, expected_generation=1, at=NOW)
        same_pixels = FaceCandidate(self.candidate.identifier, self.candidate.crop)
        self.assertEqual(self.service.verify(same_pixels, self.gate, self.decision).verdict, Verdict.UNKNOWN)

    def test_quality_invalidation_revokes_receipt_and_inflight_result(self):
        self.enroll()
        result = self.service.verify(self.candidate, self.gate, self.decision)
        self.assertTrue(self.service.is_current(result))
        self.gate.invalidate(execution=Execution.STOPPED)
        self.assertFalse(self.service.is_current(result))
        self.assertEqual(self.service.verify(self.candidate, self.gate, self.decision).verdict, Verdict.UNKNOWN)

    def test_receipts_are_bounded_unforgeable_and_session_local(self):
        self.enroll()
        self.service = OwnerVerificationService(self.store, self.verifier, max_receipts=1)
        self.gate = QualityGate(SOURCE, calibrated_policy("owner_verification"))
        assess(self.gate, synthetic_person(0))
        self.decision = self.service.assess(self.candidate, self.gate, context=context(self.candidate.crop))
        first = self.service.verify(self.candidate, self.gate, self.decision)
        second = self.service.verify(self.candidate, self.gate, self.decision)
        self.assertFalse(self.service.is_current(first))
        self.assertFalse(self.service.is_current(replace(second)))
        self.assertFalse(OwnerVerificationService(self.store, self.verifier).is_current(second))
        self.assertTrue(self.service.is_current(second))
        self.service.close_session()
        self.assertFalse(self.service.is_current(second))

    def test_cleanup_failure_cannot_produce_match_or_write_enrollment(self):
        self.enroll()
        def failure():
            raise RuntimeError("synthetic-private-candidate")
        self.verifier.forget_candidate = failure
        result = self.service.verify(self.candidate, self.gate, self.decision)
        self.assertEqual(result.verdict, Verdict.UNKNOWN)
        with self.assertRaisesRegex(OwnerError, "QUALITY_UNAVAILABLE"):
            self.enroll()
        self.assertEqual(self.store.status().generation, 1)

    def test_enrollment_cleanup_failure_prevents_template_mutation(self):
        def failure():
            raise RuntimeError("synthetic-private-candidate")
        self.verifier.forget_candidate = failure
        with self.assertRaisesRegex(OwnerError, "LOCAL_VERIFIER_CLEANUP_FAILED"):
            self.enroll()
        self.assertEqual(self.store.status().generation, 0)

    def test_oversized_template_rejected_without_replacing_current_generation(self):
        self.enroll()
        self.verifier.template = b"synthetic" * 1024
        with self.assertRaisesRegex(OwnerError, "INVALID_OWNER_TEMPLATE"):
            self.enroll()
        self.assertEqual(self.store.status().generation, 1)

    def test_null_template_never_enrolls_deletes_or_audits_as_enrollment(self):
        self.verifier.template = None
        with self.assertRaisesRegex(OwnerError, "INVALID_OWNER_TEMPLATE"):
            self.enroll()
        self.assertEqual(self.store.status(), EnrollmentStatus(False, 0))
        self.verifier.template = b"synthetic-owner-template-v1"
        self.assertEqual(self.enroll().generation, 1)
        self.verifier.template = None
        with self.assertRaisesRegex(OwnerError, "INVALID_OWNER_TEMPLATE"):
            self.enroll()
        # A verifier that returns no template must not clear the enrolled one.
        self.assertEqual(self.store.status(), EnrollmentStatus(True, 1))
        rows = self.store._db.execute("SELECT operation FROM owner_template_audit ORDER BY id").fetchall()
        self.assertEqual([row["operation"] for row in rows], [Operation.ENROLL])
        with self.assertRaisesRegex(OwnerError, "INVALID_OWNER_TEMPLATE"):
            self.store._replace(b"synthetic", PROVENANCE, operation=Operation.DELETE,
                                actor=UUID(int=123), expected_generation=1, at=NOW)
        self.assertEqual(self.store.status(), EnrollmentStatus(True, 1))

    def test_no_default_model_and_mismatched_model_are_unknown(self):
        self.enroll()
        self.service._verifier = None
        self.assertEqual(self.service.verify(self.candidate, self.gate, self.decision).reason,
                         VerificationReason.VERIFIER_UNAVAILABLE)
        self.service._verifier = self.verifier
        self.verifier.provenance = replace(PROVENANCE, version="different-fixture")
        self.assertEqual(self.service.verify(self.candidate, self.gate, self.decision).reason,
                         VerificationReason.MODEL_MISMATCH)

    def test_no_biometric_in_any_diagnostic_or_repr(self):
        self.enroll()
        result = self.service.verify(self.candidate, self.gate, self.decision)
        export = json.dumps(self.store.diagnostic_snapshot())
        self.assertEqual(set(self.store.diagnostic_snapshot()), {"enrolled", "generation"})
        for output in (export, repr(self.candidate), repr(result), repr(self.store._load_for_verification())):
            self.assertNotIn("synthetic-owner-template", output)
            self.assertNotIn(repr(self.candidate.crop.pixels), output)
        self.assertFalse(hasattr(self.store, "export_template"))
        self.assertFalse(hasattr(self.service, "enroll_non_owner"))

    def test_nonowner_candidate_never_persists_or_leaves_adapter_state(self):
        self.enroll()
        self.verifier.outcome = Comparison(Verdict.NO_MATCH, .99)
        with patch.object(socket.socket, "connect", side_effect=AssertionError("network forbidden")):
            for _ in range(4):
                self.assertEqual(self.service.verify(self.candidate, self.gate, self.decision).verdict, Verdict.NO_MATCH)
            self.service.close_session()
        self.assertEqual(self.verifier.candidates, [])
        names = {row[0] for row in self.store._db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        self.assertEqual(names, {"schema_migrations", "owner_template", "owner_template_audit"})
        self.assertEqual(self.store._db.execute("SELECT COUNT(*) FROM owner_template").fetchone()[0], 1)
        self.assertEqual(self.store._db.execute("SELECT COUNT(*) FROM owner_template_audit").fetchone()[0], 1)
        for file in self.root.iterdir():
            self.assertNotIn(self.candidate.crop.pixels, file.read_bytes())

    def test_verifier_failure_is_sanitized_unknown(self):
        self.enroll()
        earlier = self.service.verify(self.candidate, self.gate, self.decision)
        def failure():
            raise RuntimeError("synthetic-private-face-value")
        self.verifier.callback = failure
        with self.assertNoLogs():
            result = self.service.verify(self.candidate, self.gate, self.decision)
        self.assertEqual(result.verdict, Verdict.UNKNOWN)
        self.assertNotIn("synthetic-private", repr(result))
        self.assertEqual(self.verifier.candidates, [])
        self.assertFalse(self.service.is_current(earlier))

    def test_generation_conflict_and_failed_transaction_keep_old_template(self):
        self.enroll()
        with self.assertRaisesRegex(OwnerError, "GENERATION"):
            self.store.delete(expected_generation=0, at=NOW)
        self.store._db.execute("CREATE TRIGGER fail_template BEFORE UPDATE ON owner_template BEGIN SELECT RAISE(ABORT, 'synthetic-private-value'); END")
        with self.assertRaisesRegex(OwnerError, "PRIVATE_TEMPLATE_STORAGE_UNAVAILABLE"):
            self.store.delete(expected_generation=1, at=NOW)
        self.assertEqual(self.store.status().generation, 1)
        self.assertTrue(self.store.status().enrolled)
        self.assertEqual(self.store._db.execute("SELECT COUNT(*) FROM owner_template_audit").fetchone()[0], 1)

    def test_file_swapped_after_verification_never_opens_another_file(self):
        # A plain path reopen would resolve the path again and follow a symlink
        # installed after the O_NOFOLLOW checks, writing the private schema into
        # an attacker-chosen file.
        self.store.close()
        decoy = Path(self.temp.name) / "decoy.sqlite3"
        decoy.touch(mode=0o600)
        database = self.root / "owner-template.sqlite3"
        verified = OwnerTemplateStore._check
        swapped = []

        def racing_check(store):
            verified(store)
            if not swapped:
                swapped.append(True)
                database.unlink()
                database.symlink_to(decoy)

        with patch.object(OwnerTemplateStore, "_check", racing_check):
            with self.assertRaises(OwnerError):
                self.open_store()
        self.assertTrue(swapped)
        self.assertEqual(decoy.read_bytes(), b"")
        database.unlink()
        self.store = self.open_store()
        self.assertEqual(self.store.status(), EnrollmentStatus(False, 0))

    def test_substitutable_ancestor_directory_is_rejected(self):
        # SQLite re-resolves the canonical path for the rollback journal, which
        # holds pre-update pages of the Owner template, so an ancestor that
        # another user could rename or replace must not be accepted at all.
        shared = Path(self.temp.name) / "shared"
        shared.mkdir(mode=0o700)
        root = shared / "private"
        root.mkdir(mode=0o700)
        shared.chmod(0o777)
        with self.assertRaisesRegex(OwnerError, "PRIVATE_TEMPLATE_ROOT_UNSAFE_PATH"):
            self.open_store(root=root)
        self.assertEqual(list(root.iterdir()), [])
        # Sticky shared ancestors stay usable: only an entry's owner may
        # rename or unlink it there.
        shared.chmod(0o1777)
        store = self.open_store(root=root)
        self.addCleanup(store.close)
        self.assertEqual(store.status(), EnrollmentStatus(False, 0))

    def test_ancestor_made_substitutable_later_fails_closed(self):
        shared = Path(self.temp.name) / "late"
        shared.mkdir(mode=0o700)
        root = shared / "private"
        root.mkdir(mode=0o700)
        store = self.open_store(root=root)
        self.addCleanup(store.close)
        self.assertEqual(store.status(), EnrollmentStatus(False, 0))
        shared.chmod(0o777)
        with self.assertRaisesRegex(OwnerError, "PRIVATE_TEMPLATE_ROOT_UNSAFE_PATH"):
            store.delete(expected_generation=0, at=NOW)

    def test_connection_opens_through_the_verified_directory_descriptor(self):
        self.store.close()
        opened = []
        connect = sqlite3.connect

        def recording(path, **keywords):
            opened.append(str(path))
            return connect(path, **keywords)

        with patch.object(sqlite3, "connect", recording):
            self.store = self.open_store()
        # The path names the already verified descriptor, so no component of
        # the private root is resolved again after its O_NOFOLLOW checks.
        self.assertTrue(opened[0].startswith("/proc/self/fd/"), opened[0])
        self.assertEqual(os.stat(opened[0]).st_ino,
                         (self.root / "owner-template.sqlite3").stat().st_ino)

    def test_migration_drift_is_the_fixed_owner_storage_error(self):
        # Edited/newer private migration history must not leak MigrationError
        # to callers that only handle owner-store unavailability.
        for statement, parameters in (
                ("UPDATE schema_migrations SET checksum=? WHERE version=1", ("0" * 64,)),
                ("INSERT INTO schema_migrations VALUES(2,'synthetic_future',?)", ("1" * 64,))):
            with self.subTest(statement=statement.split()[0]):
                self.store.close()
                connection = sqlite3.connect(self.root / "owner-template.sqlite3", isolation_level=None)
                try:
                    connection.execute(statement, parameters)
                finally:
                    connection.close()
                with self.assertRaisesRegex(OwnerError, "PRIVATE_TEMPLATE_STORAGE_UNAVAILABLE"):
                    self.open_store()
                connection = sqlite3.connect(self.root / "owner-template.sqlite3", isolation_level=None)
                try:
                    connection.execute("DELETE FROM schema_migrations")
                    connection.execute("INSERT INTO schema_migrations VALUES(1,?,?)",
                                       (MIGRATION.name, MIGRATION.checksum))
                finally:
                    connection.close()
                self.store = self.open_store()

    def test_authorization_rechecked_after_template_creation(self):
        enroll = self.verifier.enroll
        def revoked(crop):
            template = enroll(crop)
            self.authorizer.allowed = False
            return template
        self.verifier.enroll = revoked
        with self.assertRaises(OwnerError):
            self.enroll()
        self.assertFalse(self.store.status().enrolled)

    def test_hard_stop_reservation_rejects_sensitive_writes(self):
        self.denied = True
        with self.assertRaisesRegex(OwnerError, "STORAGE_HARD_STOP"):
            self.enroll()
        self.assertEqual(self.store.status().generation, 0)

    def test_database_permissions_and_substitution_fail_closed(self):
        path = self.root / "owner-template.sqlite3"
        path.chmod(0o644)
        with self.assertRaises(OwnerError):
            self.store.status()
        path.chmod(0o600)
        path.rename(self.root / "old.sqlite3")
        path.touch(mode=0o600)
        with self.assertRaises(OwnerError):
            self.store.status()

    def test_root_substitution_does_not_create_fallback(self):
        self.root.rename(self.root.parent / "original")
        self.root.mkdir(mode=0o700)
        with self.assertRaises(OwnerError):
            self.store.status()
        self.assertEqual(list(self.root.iterdir()), [])

    def test_symlink_fifo_and_shared_permissions_are_rejected(self):
        for kind in ("symlink", "fifo", "world-readable"):
            root = self.root.parent / kind
            root.mkdir(mode=0o700)
            path = root / "owner-template.sqlite3"
            if kind == "symlink":
                path.symlink_to(self.root / "owner-template.sqlite3")
            elif kind == "fifo":
                os.mkfifo(path, 0o600)
            else:
                path.touch(mode=0o644)
            with self.subTest(kind=kind), self.assertRaises(OwnerError):
                self.open_store(root=root)

    def test_second_worker_cannot_access_template(self):
        failures = []
        def wrong_worker():
            try:
                self.store.status()
            except OwnerError as exc:
                failures.append(str(exc))
        worker = threading.Thread(target=wrong_worker)
        worker.start()
        worker.join()
        self.assertEqual(failures, ["PRIVATE_TEMPLATE_STORE_UNAVAILABLE"])

    def test_second_process_store_cannot_open_same_private_root(self):
        with self.assertRaises(OwnerError):
            self.open_store()
